-- GENERATED FILE — do not edit by hand.
-- Regenerate with: npm run db:seed:generate (source: src/lib/fixtures/).
--
-- Seeds the Phase 1 fixture books verbatim (spec #7). Both books are kept so the
-- UI-locale-vs-content-language independence rule stays verifiable end to end.

-- Pride and Prejudice (excerpt) (en) — 6 chunks
insert into books (slug, title, author, language, chunk_count)
values ('pride-and-prejudice-excerpt', 'Pride and Prejudice (excerpt)', 'Jane Austen', 'en', 6);

insert into chunks (book_id, "index", content, char_count) values
	((select id from books where slug = 'pride-and-prejudice-excerpt'), 0, 'It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.', 377),
	((select id from books where slug = 'pride-and-prejudice-excerpt'), 1, '"My dear Mr. Bennet," said his lady to him one day, "have you heard that Netherfield Park is let at last?" Mr. Bennet replied that he had not. "But it is," returned she; "for Mrs. Long has just been here, and she told me all about it." Mr. Bennet made no answer. "Do not you want to know who has taken it?" cried his wife, impatiently. "You want to tell me, and I have no objection to hearing it." This was invitation enough.', 425),
	((select id from books where slug = 'pride-and-prejudice-excerpt'), 2, '"Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England; that he came down on Monday in a chaise and four to see the place, and was so much delighted with it that he agreed with Mr. Morris immediately; that he is to take possession before Michaelmas, and some of his servants are to be in the house by the end of next week." "What is his name?" "Bingley."', 428),
	((select id from books where slug = 'pride-and-prejudice-excerpt'), 3, '"Is he married or single?" "Oh, single, my dear, to be sure! A single man of large fortune; four or five thousand a year. What a fine thing for our girls!" "How so? how can it affect them?" "My dear Mr. Bennet," replied his wife, "how can you be so tiresome? You must know that I am thinking of his marrying one of them." "Is that his design in settling here?" "Design? Nonsense, how can you talk so! But it is very likely that he may fall in love with one of them, and therefore you must visit him as soon as he comes."', 520),
	((select id from books where slug = 'pride-and-prejudice-excerpt'), 4, '"I see no occasion for that. You and the girls may go - or you may send them by themselves, which perhaps will be still better; for as you are as handsome as any of them, Mr. Bingley might like you the best of the party." "My dear, you flatter me. I certainly have had my share of beauty, but I do not pretend to be anything extraordinary now. When a woman has five grown-up daughters, she ought to give over thinking of her own beauty." "In such cases, a woman has not often much beauty to think of."', 501),
	((select id from books where slug = 'pride-and-prejudice-excerpt'), 5, '"But, my dear, you must indeed go and see Mr. Bingley when he comes into the neighbourhood." "It is more than I engage for, I assure you." "But consider your daughters. Only think what an establishment it would be for one of them. Sir William and Lady Lucas are determined to go, merely on that account; for in general, you know, they visit no new comers. Indeed you must go, for it will be impossible for us to visit him, if you do not."', 438);

-- Don Quijote de la Mancha (fragmento) (es) — 5 chunks
insert into books (slug, title, author, language, chunk_count)
values ('don-quijote-excerpt', 'Don Quijote de la Mancha (fragmento)', 'Miguel de Cervantes', 'es', 5);

insert into chunks (book_id, "index", content, char_count) values
	((select id from books where slug = 'don-quijote-excerpt'), 0, 'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino.', 557),
	((select id from books where slug = 'don-quijote-excerpt'), 1, 'Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque, por conjeturas verosímiles, se deja entender que se llamaba Quejana.', 542),
	((select id from books where slug = 'don-quijote-excerpt'), 2, 'Pero esto importa poco a nuestro cuento; basta que en la narración dél no se salga un punto de la verdad. Limpias, pues, sus armas, hecho del morrión celada, puesto nombre a su rocín y confirmándose a sí mismo, se dio a entender que no le faltaba otra cosa sino buscar una dama de quien enamorarse; porque el caballero andante sin amores era árbol sin hojas y sin fruto y cuerpo sin alma.', 388),
	((select id from books where slug = 'don-quijote-excerpt'), 3, 'Si yo, por malos de mis pecados, o por mi buena suerte, me encuentro por ahí con algún gigante, como de ordinario les acontece a los caballeros andantes, y le derribo de un encuentro, o le parto por mitad del cuerpo, o, finalmente, le venzo y le rindo, ¿no será bien tener a quien enviarle presentado y que entre y se hinque de rodillas ante mi dulce señora, y diga con voz humilde y rendido: "Yo, señora, soy el gigante Caraculiambro, señor de la ínsula Malindrania, a quien venció en singular batalla el jamás como se debe alabado caballero don Quijote de la Mancha, el cual me mandó que me presentase ante vuestra merced, para que la vuestra grandeza disponga de mí a su talante"?', 683),
	((select id from books where slug = 'don-quijote-excerpt'), 4, '¡Oh, cómo se holgó nuestro buen caballero cuando hubo hecho este discurso, y más cuando halló a quien dar nombre de su dama! Llamábase Aldonza Lorenzo, y a ésta le pareció ser bien darle título de señora de sus pensamientos; y, buscándole nombre que no desdijese mucho del suyo, y que tirase y se encaminase al de princesa y gran señora, vino a llamarla Dulcinea del Toboso, porque era natural del Toboso; nombre, a su parecer, músico y peregrino y significativo, como todos los demás que a él y a sus cosas había puesto.', 521);
